version: "3.1"

services:
  web:
    build: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
  db:
    image: mysql:latest
    ports:
      - "3311:3306"
    volumes:
      - phpwebapp_db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  phpwebapp_db_data: