version: "3.1"

services:
  web:
    build: 
      context: .
      dockerfile: ./docker/DockerfileLocal
    ports:
      - "${WEB_HTTP_PORT}:80"
      - "${WEB_HTTPS_PORT}:443"
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:latest
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    volumes:
      - phpwebapp_db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_EXTERNAL_PORT}:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  phpwebapp_db_data:
